import { connectDB } from '../config/db.js';
import { Service } from '../models/services.model.js';
import { Doctor } from '../models/doctors.model.js';
import mongoose from 'mongoose';

async function seed() {
  await connectDB();

  await Service.deleteMany({});
  await Doctor.deleteMany({});

  const services = await Service.insertMany([
    {
      name: 'Dental Implants',
      slug: 'dental-implants',
      category: 'Surgical',
      shortDescription: 'Permanent tooth replacement with a natural look and feel.',
      description: 'Titanium dental implants that replace missing teeth with a strong, natural-looking solution.',
      priceFrom: 1200,
      durationMinutes: 90,
      imageUrl: 'https://unsplash.com/photos/dental-implant-model-with-teeth-W9YEY6G8LVM?w=800&auto=format&fit=crop&q=60',
      keyBenefits: ['Permanent', 'Natural look', 'Lifetime durability'],
      process: [
        { step: 1, title: 'Consultation', description: 'Detailed imaging and treatment planning.' },
        { step: 2, title: 'Placement', description: 'Surgical insertion of titanium post.' },
        { step: 3, title: 'Recovery', description: 'Final crown fitting and full smile restoration.' },
      ],
    },
    {
      name: 'Teeth Whitening',
      slug: 'teeth-whitening',
      category: 'Cosmetic',
      shortDescription: 'Professional in-office whitening for a brighter smile.',
      description: 'Professional whitening treatment that removes stains and brightens teeth by several shades.',
      priceFrom: 250,
      durationMinutes: 45,
      imageUrl: 'https://unsplash.com/photos/young-woman-having-teeth-examined-by-dentist-in-dental-clinic-teeth-check-up-and-healthy-teeth-concept-IO1v90fDnek?w=800&auto=format&fit=crop&q=60',
      keyBenefits: ['Fast results', 'Non-invasive', 'Long-lasting brightness'],
      process: [
        { step: 1, title: 'Shade assessment', description: 'Check current tooth shade and suitability.' },
        { step: 2, title: 'Whitening session', description: 'In-office gel application under safe UV/LED light.' },
        { step: 3, title: 'Aftercare', description: 'Guidance on maintaining your brighter smile.' },
      ],
    },
    {
      name: 'Routine Cleaning',
      slug: 'routine-cleaning',
      category: 'General',
      shortDescription: 'Standard cleaning and dental examination.',
      description: 'Routine cleaning removes plaque, tartar, and helps prevent gum disease.',
      priceFrom: 80,
      durationMinutes: 30,
      imageUrl: 'https://images.pexels.com/photos/3958092/pexels-photo-3958092.jpeg?w=800&auto=format&fit=crop&q=60',
      keyBenefits: ['Prevents cavities', 'Freshens breath', 'Quick & painless'],
      process: [
        { step: 1, title: 'Examination', description: 'Check teeth and gums for early issues.' },
        { step: 2, title: 'Scaling & polishing', description: 'Remove plaque and tartar buildup.' },
        { step: 3, title: 'Fluoride finish', description: 'Optional fluoride treatment for extra protection.' },
      ],
    },
    {
      name: 'Root Canal Treatment',
      slug: 'root-canal-treatment',
      category: 'Surgical',
      shortDescription: 'Save infected teeth without extraction.',
      description: 'Removes infected pulp, disinfects canals, and restores the tooth.',
      priceFrom: 450,
      durationMinutes: 90,
      imageUrl: 'https://pixabay.com/images/download/ales_kartal-dentist-1864921_1920.jpg?w=800&auto=format&fit=crop&q=60',
      keyBenefits: ['Saves natural tooth', 'Pain relief', 'High success rate'],
      process: [
        { step: 1, title: 'Diagnosis', description: 'X-ray and assessment of the infected tooth.' },
        { step: 2, title: 'Cleaning canals', description: 'Remove infected pulp and disinfect root canals.' },
        { step: 3, title: 'Sealing & crown', description: 'Seal the tooth and fit a protective crown.' },
      ],
    },
    {
      name: 'Dental Crown',
      slug: 'dental-crown',
      category: 'General',
      shortDescription: 'Restore damaged teeth with durable crowns.',
      description: 'Custom ceramic crowns restore strength, function, and appearance.',
      priceFrom: 650,
      durationMinutes: 75,
      imageUrl: 'https://images.pexels.com/photos/12712256/pexels-photo-12712256.jpeg?w=800&auto=format&fit=crop&q=60',
      keyBenefits: ['Restores strength', 'Natural appearance', 'Durable material'],
      process: [
        { step: 1, title: 'Tooth preparation', description: 'Shape the tooth to receive the crown.' },
        { step: 2, title: 'Impression & fitting', description: 'Digital scan and temporary crown placement.' },
        { step: 3, title: 'Final placement', description: 'Bond the custom ceramic crown permanently.' },
      ],
    },
    {
      name: 'Dental Veneers',
      slug: 'dental-veneers',
      category: 'Cosmetic',
      shortDescription: 'Transform your smile with porcelain veneers.',
      description: 'Thin porcelain shells placed over teeth for a beautiful smile makeover.',
      priceFrom: 900,
      durationMinutes: 120,
      imageUrl: 'https://images.pexels.com/photos/6627572/pexels-photo-6627572.jpeg?w=800&auto=format&fit=crop&q=60',
      keyBenefits: ['Stain resistant', 'Natural translucency', 'Long-lasting'],
      process: [
        { step: 1, title: 'Smile design', description: 'Plan shape, size, and shade with the patient.' },
        { step: 2, title: 'Tooth preparation', description: 'Minimal enamel removal for a precise fit.' },
        { step: 3, title: 'Bonding', description: 'Permanently bond custom porcelain veneers.' },
      ],
    },
    {
      name: 'Braces Consultation',
      slug: 'braces-consultation',
      category: 'General',
      shortDescription: 'Comprehensive orthodontic assessment.',
      description: 'Consultation to evaluate bite alignment and recommend treatment options.',
      priceFrom: 100,
      durationMinutes: 40,
      imageUrl: 'https://images.pexels.com/photos/6528908/pexels-photo-6528908.jpeg?w=800&auto=format&fit=crop&q=60',
      keyBenefits: ['Personalized plan', 'No obligation', 'Expert assessment'],
      process: [
        { step: 1, title: 'Bite assessment', description: 'Evaluate alignment and jaw structure.' },
        { step: 2, title: 'Imaging', description: 'Digital scans or X-rays as needed.' },
        { step: 3, title: 'Treatment options', description: 'Discuss braces vs. clear aligners.' },
      ],
    },
    {
      name: 'Invisalign',
      slug: 'invisalign',
      category: 'Cosmetic',
      shortDescription: 'Clear aligners for teeth straightening.',
      description: 'Custom clear aligners designed to gradually straighten teeth.',
      priceFrom: 950,
      durationMinutes: 60,
      imageUrl: 'https://images.pexels.com/photos/28407748/pexels-photo-28407748.jpeg?w=800&auto=format&fit=crop&q=60',
      keyBenefits: ['Nearly invisible', 'Removable', 'Comfortable fit'],
      process: [
        { step: 1, title: 'Digital scan', description: '3D scan to map your teeth movement.' },
        { step: 2, title: 'Custom aligners', description: 'Receive a series of clear custom aligners.' },
        { step: 3, title: 'Progress check-ins', description: 'Periodic visits to track alignment progress.' },
      ],
    },
    {
      name: 'Tooth Extraction',
      slug: 'tooth-extraction',
      category: 'Surgical',
      shortDescription: 'Safe removal of damaged or impacted teeth.',
      description: 'Simple and surgical tooth extraction procedures with local anesthesia.',
      priceFrom: 200,
      durationMinutes: 45,
      imageUrl: 'https://images.pexels.com/photos/6627559/pexels-photo-6627559.jpeg?w=800&auto=format&fit=crop&q=60',
      keyBenefits: ['Fast pain relief', 'Local anesthesia', 'Prevents further damage'],
      process: [
        { step: 1, title: 'Assessment', description: 'X-ray to plan the safest extraction approach.' },
        { step: 2, title: 'Extraction', description: 'Gentle removal of the tooth under anesthesia.' },
        { step: 3, title: 'Aftercare', description: 'Guidance for a smooth, infection-free recovery.' },
      ],
    },
    {
      name: 'Pediatric Dental Checkup',
      slug: 'pediatric-dental-checkup',
      category: 'General',
      shortDescription: 'Comprehensive dental care for children.',
      description: 'Routine dental examination, cleaning, and preventive treatments for children.',
      priceFrom: 90,
      durationMinutes: 30,
      imageUrl: 'https://images.pexels.com/photos/6502542/pexels-photo-6502542.jpeg?w=800&auto=format&fit=crop&q=60',
      keyBenefits: ['Kid-friendly care', 'Early problem detection', 'Builds healthy habits'],
      process: [
        { step: 1, title: 'Friendly welcome', description: 'A relaxed, fun introduction to the clinic.' },
        { step: 2, title: 'Gentle examination', description: 'Check for cavities and healthy development.' },
        { step: 3, title: 'Cleaning & tips', description: 'Light cleaning plus at-home hygiene tips.' },
      ],
    },
    {
      name: 'Emergency Dental Care',
      slug: 'emergency-dental-care',
      category: 'Surgical',
      shortDescription: 'Immediate treatment for dental emergencies.',
      description: 'Emergency care for severe tooth pain, broken teeth, infections, and trauma.',
      priceFrom: 180,
      durationMinutes: 60,
      imageUrl: 'https://images.pexels.com/photos/14624608/pexels-photo-14624608.jpeg?w=800&auto=format&fit=crop&q=60',
      keyBenefits: ['Same-day availability', 'Rapid pain relief', '24/7 triage advice'],
      process: [
        { step: 1, title: 'Immediate triage', description: 'Quick phone or in-person assessment of urgency.' },
        { step: 2, title: 'Stabilization', description: 'Pain management and emergency treatment.' },
        { step: 3, title: 'Follow-up plan', description: 'Schedule any necessary follow-up procedures.' },
      ],
    },
    {
      name: 'Deep Teeth Cleaning',
      slug: 'deep-teeth-cleaning',
      category: 'General',
      shortDescription: 'Advanced cleaning for healthier gums.',
      description: 'Deep scaling and root planing to treat gum disease and maintain oral health.',
      priceFrom: 350,
      durationMinutes: 60,
      imageUrl: 'https://images.pexels.com/photos/5622010/pexels-photo-5622010.jpeg?w=800&auto=format&fit=crop&q=60',
      keyBenefits: ['Treats gum disease', 'Reduces inflammation', 'Protects tooth roots'],
      process: [
        { step: 1, title: 'Periodontal exam', description: 'Measure gum pockets and assess gum health.' },
        { step: 2, title: 'Scaling & root planing', description: 'Deep clean below the gumline.' },
        { step: 3, title: 'Maintenance plan', description: 'Ongoing care schedule to protect gum health.' },
      ],
    },
    {
      name: 'Smile Makeover Consultation',
      slug: 'smile-makeover-consultation',
      category: 'Cosmetic',
      shortDescription: 'Personalized smile enhancement consultation.',
      description: 'Comprehensive consultation to create a customized cosmetic dentistry treatment plan.',
      priceFrom: 150,
      durationMinutes: 45,
      imageUrl: 'https://images.pexels.com/photos/12635375/pexels-photo-12635375.jpeg?w=800&auto=format&fit=crop&q=60',
      keyBenefits: ['Tailored to you', 'No-pressure planning', 'Combines multiple treatments'],
      process: [
        { step: 1, title: 'Goals discussion', description: 'Understand what you want to change about your smile.' },
        { step: 2, title: 'Digital preview', description: 'Visualize potential results before committing.' },
        { step: 3, title: 'Custom roadmap', description: 'Receive a step-by-step cosmetic treatment plan.' },
      ],
    },
    {
      name: 'Dental Filling',
      slug: 'dental-filling',
      category: 'General',
      shortDescription: 'Repair cavities using tooth-colored fillings.',
      description: 'Composite fillings restore decayed teeth while maintaining a natural appearance.',
      priceFrom: 120,
      durationMinutes: 40,
      imageUrl: 'https://images.pexels.com/photos/5622016/pexels-photo-5622016.jpeg?w=800&auto=format&fit=crop&q=60',
      keyBenefits: ['Tooth-colored', 'Same-day treatment', 'Preserves healthy tooth'],
      process: [
        { step: 1, title: 'Numb & clean', description: 'Numb the area and remove decayed tissue.' },
        { step: 2, title: 'Fill the cavity', description: 'Apply and shape a composite resin filling.' },
        { step: 3, title: 'Polish & bite check', description: 'Polish the filling and check your bite.' },
      ],
    },
    {
      name: 'Wisdom Tooth Removal',
      slug: 'wisdom-tooth-removal',
      category: 'Surgical',
      shortDescription: 'Removal of impacted wisdom teeth.',
      description: 'Surgical extraction of wisdom teeth to prevent pain and future complications.',
      priceFrom: 500,
      durationMinutes: 90,
      imageUrl: 'https://images.pexels.com/photos/6627559/pexels-photo-6627559.jpeg?w=800&auto=format&fit=crop&q=60',
      keyBenefits: ['Prevents crowding', 'Reduces infection risk', 'Sedation options available'],
      process: [
        { step: 1, title: 'Imaging & planning', description: '3D imaging to map tooth position and roots.' },
        { step: 2, title: 'Surgical removal', description: 'Extraction under local or sedation anesthesia.' },
        { step: 3, title: 'Recovery guidance', description: 'Post-op care instructions for smooth healing.' },
      ],
    },
  ]);

  await Doctor.insertMany([
    {
      name: 'Dr. Sarah Chen',
      consultationFee: 60,
      specialty: 'Orthodontist',
      bio: 'Dr. Sarah Chen is a board-certified orthodontist with a passion for creating beautiful, confident smiles. She specializes in Invisalign and traditional braces for patients of all ages.',
      photoUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 124,
      experience: '12 Years Experience',
      education: 'DDS, Harvard Medical School',
      languages: ['English', 'Spanish'],
      services: [services[6]._id, services[7]._id, services[1]._id],
      workingHours: [
        { day: 'monday', startTime: '09:00', endTime: '17:00' },
        { day: 'wednesday', startTime: '09:00', endTime: '17:00' },
        { day: 'friday', startTime: '09:00', endTime: '14:00' },
      ],
      slotDurationMinutes: 30,
    },
    {
      name: 'Dr. James Okafor',
      consultationFee: 40,
      specialty: 'General Dentist',
      bio: 'Dr. James Okafor provides comprehensive general dentistry services with a focus on preventive care and patient education. He believes in building long-term relationships with his patients.',
      photoUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=500&fit=crop',
      rating: 5.0,
      reviews: 89,
      experience: '15 Years Experience',
      education: 'MDS, Stanford University',
      languages: ['English', 'French'],
      services: [services[2]._id, services[10]._id, services[8]._id],
      workingHours: [
        { day: 'tuesday', startTime: '10:00', endTime: '18:00' },
        { day: 'thursday', startTime: '10:00', endTime: '18:00' },
        { day: 'saturday', startTime: '09:00', endTime: '13:00' },
      ],
      slotDurationMinutes: 30,
    },
    {
      name: 'Dr. Emily Rodriguez',
      consultationFee: 75,
      specialty: 'Cosmetic Dentist',
      bio: 'Dr. Emily Rodriguez is a renowned cosmetic dentist with a reputation for creating stunning smile makeovers. She specializes in veneers, teeth whitening, and full-mouth restorations.',
      photoUrl: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 210,
      experience: '18 Years Experience',
      education: 'DDS, Yale University',
      languages: ['English', 'Mandarin'],
      services: [services[1]._id, services[5]._id, services[4]._id],
      workingHours: [
        { day: 'monday', startTime: '11:00', endTime: '18:00' },
        { day: 'tuesday', startTime: '09:00', endTime: '17:00' },
        { day: 'thursday', startTime: '09:00', endTime: '17:00' },
      ],
      slotDurationMinutes: 45,
    },
    {
      name: 'Dr. Michael Johnson',
      consultationFee: 90,
      specialty: 'Oral Surgeon',
      bio: 'Dr. Michael Johnson is an experienced oral and maxillofacial surgeon specializing in wisdom teeth extraction, dental implants, and corrective jaw surgery.',
      photoUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=500&fit=crop',
      rating: 4.7,
      reviews: 143,
      experience: '14 Years Experience',
      education: 'MD, DDS, Columbia University',
      languages: ['English', 'Korean'],
      services: [services[0]._id, services[8]._id, services[3]._id],
      workingHours: [
        { day: 'wednesday', startTime: '08:00', endTime: '16:00' },
        { day: 'friday', startTime: '08:00', endTime: '16:00' },
      ],
      slotDurationMinutes: 60,
    },
    {
      name: 'Dr. Olivia Brown',
      consultationFee: 45,
      specialty: 'Pediatric Dentist',
      bio: 'Dr. Olivia Brown creates a fun and welcoming environment for children. She specializes in pediatric dentistry and helps kids develop healthy oral hygiene habits early.',
      photoUrl: 'https://images.unsplash.com/photo-1591604021695-0c69b7c05981?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 178,
      experience: '10 Years Experience',
      education: 'DMD, UCLA School of Dentistry',
      languages: ['English', 'Spanish'],
      services: [services[9]._id, services[2]._id],
      workingHours: [
        { day: 'monday', startTime: '09:00', endTime: '15:00' },
        { day: 'wednesday', startTime: '09:00', endTime: '15:00' },
        { day: 'friday', startTime: '09:00', endTime: '15:00' },
      ],
      slotDurationMinutes: 30,
    },
    {
      name: 'Dr. Ahmed Hassan',
      consultationFee: 70,
      specialty: 'Periodontist',
      bio: 'Dr. Ahmed Hassan is a specialist in periodontics and implantology. He is dedicated to saving natural teeth and restoring oral health through advanced surgical techniques.',
      photoUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=500&fit=crop',
      rating: 4.8,
      reviews: 156,
      experience: '8 Years Experience',
      education: 'DMD, University of Miami',
      languages: ['English', 'Portuguese'],
      services: [services[11]._id, services[0]._id, services[4]._id],
      workingHours: [
        { day: 'tuesday', startTime: '08:30', endTime: '16:30' },
        { day: 'thursday', startTime: '08:30', endTime: '16:30' },
      ],
      slotDurationMinutes: 45,
    },
    {
      name: 'Dr. Sophia Williams',
      consultationFee: 65,
      specialty: 'Endodontist',
      bio: 'Dr. Sophia Williams is a root canal specialist who uses advanced technology to provide comfortable and efficient endodontic treatments. She is dedicated to saving natural teeth.',
      photoUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400&h=500&fit=crop',
      rating: 4.8,
      reviews: 132,
      experience: '11 Years Experience',
      education: 'DDS, University of Michigan',
      languages: ['English', 'German'],
      services: [services[3]._id, services[4]._id],
      workingHours: [
        { day: 'monday', startTime: '10:00', endTime: '17:00' },
        { day: 'friday', startTime: '10:00', endTime: '17:00' },
      ],
      slotDurationMinutes: 60,
    },
    {
      name: 'Dr. Robert Johnson',
      consultationFee: 85,
      specialty: 'Prosthodontist',
      bio: 'Dr. Robert Johnson specializes in complex restorative and prosthetic dentistry. He creates natural-looking crowns, bridges, and dentures that restore function and aesthetics.',
      photoUrl: 'https://images.unsplash.com/photo-1637059824899-a441006a6875?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 167,
      experience: '20 Years Experience',
      education: 'DDS, University of Pennsylvania',
      languages: ['English', 'Italian'],
      services: [services[4]._id, services[0]._id, services[12]._id],
      workingHours: [
        { day: 'tuesday', startTime: '09:00', endTime: '17:00' },
        { day: 'wednesday', startTime: '09:00', endTime: '17:00' },
        { day: 'saturday', startTime: '10:00', endTime: '14:00' },
      ],
      slotDurationMinutes: 45,
    },
    {
      name: 'Dr. Chloe Dubois',
      consultationFee: 55,
      specialty: 'Orthodontist',
      bio: 'Dr. Chloe Dubois is passionate about high-tech orthodontics, utilizing digital mapping to craft seamless aligner pathways and traditional tracking styles for children and adults.',
      photoUrl: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=500&fit=crop',
      rating: 4.6,
      reviews: 94,
      experience: '9 Years Experience',
      education: 'DDS, McGill University',
      languages: ['English', 'French'],
      services: [services[6]._id, services[7]._id],
      workingHours: [
        { day: 'tuesday', startTime: '09:00', endTime: '16:00' },
        { day: 'thursday', startTime: '09:00', endTime: '16:00' },
      ],
      slotDurationMinutes: 30,
    },
    {
      name: 'Dr. Marcus Vance',
      consultationFee: 80,
      specialty: 'Oral Surgeon',
      bio: 'Dr. Marcus Vance brings precise structural focus to heavy extractions and dental implants. He leads complex surgical reconstructions with tailored post-care programs.',
      photoUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 188,
      experience: '16 Years Experience',
      education: 'DDS, Johns Hopkins University',
      languages: ['English'],
      services: [services[0]._id, services[14]._id, services[10]._id],
      workingHours: [
        { day: 'monday', startTime: '08:00', endTime: '15:00' },
        { day: 'thursday', startTime: '08:00', endTime: '17:00' },
      ],
      slotDurationMinutes: 60,
    },
    {
      name: 'Dr. Priya Patel',
      consultationFee: 35,
      specialty: 'General Dentist',
      bio: 'Dr. Priya Patel combines empathetic dental approaches with progressive preventive care. Her daily focus centers around comfortable routine maintenance and aesthetic fillings.',
      photoUrl: 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?w=400&h=500&fit=crop',
      rating: 4.8,
      reviews: 112,
      experience: '7 Years Experience',
      education: 'BDS, King\'s College London',
      languages: ['English', 'Hindi', 'Gujarati'],
      services: [services[2]._id, services[13]._id, services[11]._id],
      workingHours: [
        { day: 'wednesday', startTime: '09:00', endTime: '17:00' },
        { day: 'friday', startTime: '09:00', endTime: '17:00' },
        { day: 'saturday', startTime: '08:00', endTime: '12:00' },
      ],
      slotDurationMinutes: 30,
    },
    {
      name: 'Dr. Alexander Novak',
      consultationFee: 70,
      specialty: 'Cosmetic Dentist',
      bio: 'Dr. Alexander Novak transforms clinical dentistry into creative art. Specializing in minimal-prep custom porcelain veneers and laser brightness upgrades.',
      photoUrl: 'https://images.unsplash.com/photo-1637059824899-a441006a6875?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 245,
      experience: '13 Years Experience',
      education: 'DDS, NYU College of Dentistry',
      languages: ['English', 'Russian'],
      services: [services[1]._id, services[5]._id, services[12]._id],
      workingHours: [
        { day: 'monday', startTime: '10:00', endTime: '19:00' },
        { day: 'wednesday', startTime: '10:00', endTime: '19:00' },
      ],
      slotDurationMinutes: 45,
    },
    {
      name: 'Dr. Lucas Gallagher',
      consultationFee: 50,
      specialty: 'Endodontist',
      bio: 'Dr. Lucas Gallagher targets pain-free endodontic therapy using micro-dentistry tools. He treats microscopic fractures and saves complex compromised root configurations.',
      photoUrl: 'https://images.unsplash.com/photo-1637059824899-a441006a6875?w=400&h=500&fit=crop',
      rating: 4.7,
      reviews: 76,
      experience: '6 Years Experience',
      education: 'DMD, Boston University',
      languages: ['English'],
      services: [services[3]._id, services[10]._id],
      workingHours: [
        { day: 'tuesday', startTime: '08:00', endTime: '16:00' },
        { day: 'friday', startTime: '08:00', endTime: '15:00' },
      ],
      slotDurationMinutes: 60,
    },
    {
      name: 'Dr. Elena Rostova',
      consultationFee: 45,
      specialty: 'Pediatric Dentist',
      bio: 'Dr. Elena Rostova makes scary dental tools look like toys. Her custom behavioral pacing techniques guarantee tear-free cleanings and early structural cavity checks.',
      photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=500&fit=crop',
      rating: 5.0,
      reviews: 194,
      experience: '11 Years Experience',
      education: 'DDS, University of Toronto',
      languages: ['English', 'Ukrainian'],
      services: [services[9]._id, services[2]._id, services[13]._id],
      workingHours: [
        { day: 'tuesday', startTime: '09:00', endTime: '16:00' },
        { day: 'thursday', startTime: '09:00', endTime: '16:00' },
        { day: 'saturday', startTime: '09:00', endTime: '14:00' },
      ],
      slotDurationMinutes: 30,
    },
    {
      name: 'Dr. Yusuf Al-Mansoor',
      consultationFee: 60,
      specialty: 'Periodontist',
      bio: 'Dr. Yusuf Al-Mansoor targets complex gum pocket treatments and deep osseous grafting, restoring structural bone loss caused by aggressive advancements of periodontal conditions.',
      photoUrl: 'https://images.unsplash.com/photo-1625498542602-6bfb30f39b3f?w=400&h=500&fit=crop',
      rating: 4.8,
      reviews: 103,
      experience: '10 Years Experience',
      education: 'DMD, Tufts University',
      languages: ['English', 'Arabic'],
      services: [services[11]._id, services[8]._id],
      workingHours: [
        { day: 'monday', startTime: '08:30', endTime: '16:30' },
        { day: 'wednesday', startTime: '08:30', endTime: '16:30' },
      ],
      slotDurationMinutes: 45,
    },
    {
      name: 'Dr. Natalie Vance',
      consultationFee: 75,
      specialty: 'Prosthodontist',
      bio: 'Dr. Natalie Vance structures comprehensive occlusal bite adjustments, designing permanent implant crowns and beautiful hybrid restorations that feel perfectly natural.',
      photoUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 137,
      experience: '14 Years Experience',
      education: 'DDS, University of Washington',
      languages: ['English'],
      services: [services[4]._id, services[0]._id, services[12]._id],
      workingHours: [
        { day: 'wednesday', startTime: '09:00', endTime: '17:00' },
        { day: 'thursday', startTime: '09:00', endTime: '17:00' },
        { day: 'friday', startTime: '09:00', endTime: '16:00' },
      ],
      slotDurationMinutes: 45,
    },
    {
      name: 'Dr. Kenji Tanaka',
      consultationFee: 40,
      specialty: 'General Dentist',
      bio: 'Dr. Kenji Tanaka values direct honesty and minimally invasive drill protocols. Known for seamless composite matching on direct multi-surface functional fillings.',
      photoUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=500&fit=crop',
      rating: 4.7,
      reviews: 82,
      experience: '9 Years Experience',
      education: 'DDS, Osaka University',
      languages: ['English', 'Japanese'],
      services: [services[2]._id, services[13]._id, services[10]._id],
      workingHours: [
        { day: 'monday', startTime: '09:00', endTime: '18:00' },
        { day: 'tuesday', startTime: '09:00', endTime: '18:00' },
      ],
      slotDurationMinutes: 30,
    },
    {
      name: 'Dr. Simone Gatti',
      consultationFee: 95,
      specialty: 'Cosmetic Dentist',
      bio: 'Dr. Simone Gatti constructs customized celebrity grade transformations. Her unique style utilizes rapid clinical whitening and state of the art ultra thin composite veneers.',
      photoUrl: 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 312,
      experience: '22 Years Experience',
      education: 'DMD, University of Milan',
      languages: ['English', 'Italian'],
      services: [services[1]._id, services[5]._id, services[12]._id],
      workingHours: [
        { day: 'thursday', startTime: '10:00', endTime: '20:00' },
        { day: 'friday', startTime: '10:00', endTime: '17:00' },
      ],
      slotDurationMinutes: 45,
    },
    {
      name: 'Dr. Christopher Lee',
      consultationFee: 85,
      specialty: 'Oral Surgeon',
      bio: 'Dr. Christopher Lee executes complicated wisdom extractions and anchors durable titanium frameworks under continuous gentle sedation practices for maximal patient ease.',
      photoUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=500&fit=crop',
      rating: 4.8,
      reviews: 165,
      experience: '13 Years Experience',
      education: 'MD, DDS, UC San Francisco',
      languages: ['English', 'Mandarin'],
      services: [services[0]._id, services[14]._id, services[8]._id],
      workingHours: [
        { day: 'tuesday', startTime: '07:30', endTime: '16:00' },
        { day: 'wednesday', startTime: '07:30', endTime: '16:00' },
      ],
      slotDurationMinutes: 60,
    },
    {
      name: 'Dr. Hannah Abas',
      consultationFee: 35,
      specialty: 'General Dentist',
      bio: 'Dr. Hannah Abas delivers highly detailed primary oral evaluations. She specializes in handling high-anxiety emergency walk-ins, providing prompt stabilization and gentle emergency options.',
      photoUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=500&fit=crop',
      rating: 4.9,
      reviews: 97,
      experience: '8 Years Experience',
      education: 'DDS, University of Jordan',
      languages: ['English', 'Arabic'],
      services: [services[2]._id, services[10]._id, services[13]._id],
      workingHours: [
        { day: 'thursday', startTime: '09:00', endTime: '18:00' },
        { day: 'saturday', startTime: '09:00', endTime: '16:00' },
      ],
      slotDurationMinutes: 30,
    },
  ]);

  console.log('[seed] done: 15 services, 20 doctors created');
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error('[seed] failed:', err);
  process.exit(1);
});